//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.12 at 05:42:24 PM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomProduct"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://teecu.be/toe-installer/environments}Product"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="installCommand" type="{http://teecu.be/toe-installer/environments}Command"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomProduct", propOrder = {
    "installCommand"
})
public class CustomProduct
    extends Product
{

    @XmlElement(required = true)
    protected Command installCommand;

    /**
     * Gets the value of the installCommand property.
     * 
     * @return
     *     possible object is
     *     {@link Command }
     *     
     */
    public Command getInstallCommand() {
        return installCommand;
    }

    /**
     * Sets the value of the installCommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Command }
     *     
     */
    public void setInstallCommand(Command value) {
        this.installCommand = value;
    }

}
