//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.29 at 04:42:44 PM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the t3.toe.installer.environments package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: t3.toe.installer.environments
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UncompressCommand }
     * 
     */
    public UncompressCommand createUncompressCommand() {
        return new UncompressCommand();
    }

    /**
     * Create an instance of {@link MavenCommand }
     * 
     */
    public MavenCommand createMavenCommand() {
        return new MavenCommand();
    }

    /**
     * Create an instance of {@link MavenCommand.Properties }
     * 
     */
    public MavenCommand.Properties createMavenCommandProperties() {
        return new MavenCommand.Properties();
    }

    /**
     * Create an instance of {@link AntCommand }
     * 
     */
    public AntCommand createAntCommand() {
        return new AntCommand();
    }

    /**
     * Create an instance of {@link AntCommand.Properties }
     * 
     */
    public AntCommand.Properties createAntCommandProperties() {
        return new AntCommand.Properties();
    }

    /**
     * Create an instance of {@link TIBCOProduct }
     * 
     */
    public TIBCOProduct createTIBCOProduct() {
        return new TIBCOProduct();
    }

    /**
     * Create an instance of {@link Environment }
     * 
     */
    public Environment createEnvironment() {
        return new Environment();
    }

    /**
     * Create an instance of {@link Environments }
     * 
     */
    public Environments createEnvironments() {
        return new Environments();
    }

    /**
     * Create an instance of {@link t3.toe.installer.environments.Property }
     * 
     */
    public t3.toe.installer.environments.Property createProperty() {
        return new t3.toe.installer.environments.Property();
    }

    /**
     * Create an instance of {@link LocalFileWithVersion }
     * 
     */
    public LocalFileWithVersion createLocalFileWithVersion() {
        return new LocalFileWithVersion();
    }

    /**
     * Create an instance of {@link LocalPackagePattern }
     * 
     */
    public LocalPackagePattern createLocalPackagePattern() {
        return new LocalPackagePattern();
    }

    /**
     * Create an instance of {@link HttpRemotePackage }
     * 
     */
    public HttpRemotePackage createHttpRemotePackage() {
        return new HttpRemotePackage();
    }

    /**
     * Create an instance of {@link MavenArtifactPackage }
     * 
     */
    public MavenArtifactPackage createMavenArtifactPackage() {
        return new MavenArtifactPackage();
    }

    /**
     * Create an instance of {@link MavenTIBCOArtifactPackage }
     * 
     */
    public MavenTIBCOArtifactPackage createMavenTIBCOArtifactPackage() {
        return new MavenTIBCOArtifactPackage();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link CustomProduct }
     * 
     */
    public CustomProduct createCustomProduct() {
        return new CustomProduct();
    }

    /**
     * Create an instance of {@link SystemCommand }
     * 
     */
    public SystemCommand createSystemCommand() {
        return new SystemCommand();
    }

    /**
     * Create an instance of {@link Commands }
     * 
     */
    public Commands createCommands() {
        return new Commands();
    }

    /**
     * Create an instance of {@link UncompressCommand.Destination }
     * 
     */
    public UncompressCommand.Destination createUncompressCommandDestination() {
        return new UncompressCommand.Destination();
    }

    /**
     * Create an instance of {@link MavenCommand.Goals }
     * 
     */
    public MavenCommand.Goals createMavenCommandGoals() {
        return new MavenCommand.Goals();
    }

    /**
     * Create an instance of {@link MavenCommand.Profiles }
     * 
     */
    public MavenCommand.Profiles createMavenCommandProfiles() {
        return new MavenCommand.Profiles();
    }

    /**
     * Create an instance of {@link MavenCommand.Properties.Property }
     * 
     */
    public MavenCommand.Properties.Property createMavenCommandPropertiesProperty() {
        return new MavenCommand.Properties.Property();
    }

    /**
     * Create an instance of {@link AntCommand.Properties.Property }
     * 
     */
    public AntCommand.Properties.Property createAntCommandPropertiesProperty() {
        return new AntCommand.Properties.Property();
    }

    /**
     * Create an instance of {@link t3.toe.installer.environments.Product.Properties }
     * 
     */
    public t3.toe.installer.environments.Product.Properties createProductProperties() {
        return new t3.toe.installer.environments.Product.Properties();
    }

    /**
     * Create an instance of {@link TIBCOProduct.Hotfixes }
     * 
     */
    public TIBCOProduct.Hotfixes createTIBCOProductHotfixes() {
        return new TIBCOProduct.Hotfixes();
    }

    /**
     * Create an instance of {@link Environment.Products }
     * 
     */
    public Environment.Products createEnvironmentProducts() {
        return new Environment.Products();
    }

}
