//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.30 at 11:18:01 AM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Package complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Package"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="httpRemote" type="{http://teecu.be/toe-installer/environments}HttpRemotePackage"/&gt;
 *         &lt;element name="mavenArtifact" type="{http://teecu.be/toe-installer/environments}MavenArtifactPackage"/&gt;
 *         &lt;element name="mavenTIBCOArtifact" type="{http://teecu.be/toe-installer/environments}MavenTIBCOArtifactPackage"/&gt;
 *         &lt;element name="fileWithVersion" type="{http://teecu.be/toe-installer/environments}LocalFileWithVersion"/&gt;
 *         &lt;element name="directoryWithPattern" type="{http://teecu.be/toe-installer/environments}LocalPackagePattern"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Package", propOrder = {
    "httpRemote",
    "mavenArtifact",
    "mavenTIBCOArtifact",
    "fileWithVersion",
    "directoryWithPattern"
})
public class Package {

    protected HttpRemotePackage httpRemote;
    protected MavenArtifactPackage mavenArtifact;
    protected MavenTIBCOArtifactPackage mavenTIBCOArtifact;
    protected LocalFileWithVersion fileWithVersion;
    protected LocalPackagePattern directoryWithPattern;

    /**
     * Gets the value of the httpRemote property.
     * 
     * @return
     *     possible object is
     *     {@link HttpRemotePackage }
     *     
     */
    public HttpRemotePackage getHttpRemote() {
        return httpRemote;
    }

    /**
     * Sets the value of the httpRemote property.
     * 
     * @param value
     *     allowed object is
     *     {@link HttpRemotePackage }
     *     
     */
    public void setHttpRemote(HttpRemotePackage value) {
        this.httpRemote = value;
    }

    /**
     * Gets the value of the mavenArtifact property.
     * 
     * @return
     *     possible object is
     *     {@link MavenArtifactPackage }
     *     
     */
    public MavenArtifactPackage getMavenArtifact() {
        return mavenArtifact;
    }

    /**
     * Sets the value of the mavenArtifact property.
     * 
     * @param value
     *     allowed object is
     *     {@link MavenArtifactPackage }
     *     
     */
    public void setMavenArtifact(MavenArtifactPackage value) {
        this.mavenArtifact = value;
    }

    /**
     * Gets the value of the mavenTIBCOArtifact property.
     * 
     * @return
     *     possible object is
     *     {@link MavenTIBCOArtifactPackage }
     *     
     */
    public MavenTIBCOArtifactPackage getMavenTIBCOArtifact() {
        return mavenTIBCOArtifact;
    }

    /**
     * Sets the value of the mavenTIBCOArtifact property.
     * 
     * @param value
     *     allowed object is
     *     {@link MavenTIBCOArtifactPackage }
     *     
     */
    public void setMavenTIBCOArtifact(MavenTIBCOArtifactPackage value) {
        this.mavenTIBCOArtifact = value;
    }

    /**
     * Gets the value of the fileWithVersion property.
     * 
     * @return
     *     possible object is
     *     {@link LocalFileWithVersion }
     *     
     */
    public LocalFileWithVersion getFileWithVersion() {
        return fileWithVersion;
    }

    /**
     * Sets the value of the fileWithVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalFileWithVersion }
     *     
     */
    public void setFileWithVersion(LocalFileWithVersion value) {
        this.fileWithVersion = value;
    }

    /**
     * Gets the value of the directoryWithPattern property.
     * 
     * @return
     *     possible object is
     *     {@link LocalPackagePattern }
     *     
     */
    public LocalPackagePattern getDirectoryWithPattern() {
        return directoryWithPattern;
    }

    /**
     * Sets the value of the directoryWithPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocalPackagePattern }
     *     
     */
    public void setDirectoryWithPattern(LocalPackagePattern value) {
        this.directoryWithPattern = value;
    }

}
