//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.02 at 02:47:19 PM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductOnErrorBehaviour.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProductOnErrorBehaviour"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="fail"/&gt;
 *     &lt;enumeration value="continue"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProductOnErrorBehaviour")
@XmlEnum
public enum ProductOnErrorBehaviour {

    @XmlEnumValue("fail")
    FAIL("fail"),
    @XmlEnumValue("continue")
    CONTINUE("continue");
    private final String value;

    ProductOnErrorBehaviour(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProductOnErrorBehaviour fromValue(String v) {
        for (ProductOnErrorBehaviour c: ProductOnErrorBehaviour.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
