//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.13 at 05:21:37 PM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UncompressCommand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UncompressCommand"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://teecu.be/toe-installer/environments}AbstractCommand"&gt;
 *       &lt;attribute name="format" type="{http://teecu.be/toe-installer/environments}UncompressFormat" default="auto" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UncompressCommand")
public class UncompressCommand
    extends AbstractCommand
{

    @XmlAttribute(name = "format")
    protected UncompressFormat format;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link UncompressFormat }
     *     
     */
    public UncompressFormat getFormat() {
        if (format == null) {
            return UncompressFormat.AUTO;
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link UncompressFormat }
     *     
     */
    public void setFormat(UncompressFormat value) {
        this.format = value;
    }

}
