//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.20 at 05:07:57 PM CEST 
//


package t3.toe.installer.environments;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UncompressCommand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UncompressCommand"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://teecu.be/toe-installer/environments}AbstractCommand"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="destinationDirectory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="format" type="{http://teecu.be/toe-installer/environments}UncompressFormat" default="auto" /&gt;
 *       &lt;attribute name="toTempDirectory" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UncompressCommand", propOrder = {
    "destinationDirectory"
})
public class UncompressCommand
    extends AbstractCommand
{

    protected String destinationDirectory;
    @XmlAttribute(name = "format")
    protected UncompressFormat format;
    @XmlAttribute(name = "toTempDirectory")
    protected Boolean toTempDirectory;

    /**
     * Gets the value of the destinationDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationDirectory() {
        return destinationDirectory;
    }

    /**
     * Sets the value of the destinationDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationDirectory(String value) {
        this.destinationDirectory = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link UncompressFormat }
     *     
     */
    public UncompressFormat getFormat() {
        if (format == null) {
            return UncompressFormat.AUTO;
        } else {
            return format;
        }
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link UncompressFormat }
     *     
     */
    public void setFormat(UncompressFormat value) {
        this.format = value;
    }

    /**
     * Gets the value of the toTempDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isToTempDirectory() {
        if (toTempDirectory == null) {
            return false;
        } else {
            return toTempDirectory;
        }
    }

    /**
     * Sets the value of the toTempDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setToTempDirectory(Boolean value) {
        this.toTempDirectory = value;
    }

}
