//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.10 at 11:38:57 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tibco.com/envInfo", elementFormDefault =  javax.xml.bind.annotation.XmlNsForm.UNQUALIFIED)
package com.tibco.envinfo;
